MvcProject/Controllers/AdminCategoryController.cs
using BusinessLayer.Concretes;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concretes;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        public ActionResult Index()
        {
            var categoryvalues = categoryManager.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(category);

            if (results.IsValid)
            {
                categoryManager.CategoryAddBL(category);
                return RedirectToAction("Index");
            }
            else {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult DeleteCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            categoryManager.CategoryDelete(categoryValue);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult UpdateCategory(int id)
        {
            var categoryValue = categoryManager.GetById(id);
            
            return View(categoryValue);
        }
        [HttpPost]
        public ActionResult UpdateCategory(Category category)
        {
            categoryManager.CategoryUpdate(category);
            return RedirectToAction("Index");
        }
    }
}

MvcProject/Controllers/CategoryController.cs
using BusinessLayer.Concretes;
using BusinessLayer.ValidationRules;
using DataAccessLayer.Abstracts;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concretes;
using FluentValidation;
using FluentValidation.Results;
using System;
using System.Collections.Generic;

using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager categoryManager = new CategoryManager(new EfCategoryDal());
        // GET: Category
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetCategoryList()
        {
            var categoryvalues = categoryManager.GetList();
            return View(categoryvalues);
        }
        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddCategory(Category category)
        {
            //  categoryManager.CategoryAddBL(category);
            CategoryValidator categoryValidator = new CategoryValidator();
            //validation results ı tutacak
            ValidationResult results = categoryValidator.Validate(category);
            if (results.IsValid)
            {
                categoryManager.CategoryAddBL(category);
                return RedirectToAction("GetCategoryList");
            }
            else
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName,item.ErrorMessage);
                }
            return View();
        }
         
    }
}

MvcProject/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Test()
        {
            return View();
        }
    }
}

MvcProject/Controllers/StatisticController.cs
using DataAccessLayer.Concretes;
using System;
using System.Collections.Generic;

using System.Linq;

using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class StatisticController : Controller
    {
        Context _context = new Context();

        public ActionResult Index()
        {
            //Toplam kategori sayısı
            var totalCategories = _context.Categories.Count();
            ViewBag.totalCategories = totalCategories;

            //Başlık tablosunda "yazılım" kategorisine ait başlık sayısı
            var softwareCategory = _context.Headings.Count(x=> x.CategoryId == 7);
            ViewBag.softwareCategory = softwareCategory;

            // Yazar adında 'a' harfi geçen yazar sayısı
            var writerNameWithA = _context.Writers.Count(x => x.WriterName.Contains("a"));
            ViewBag.writerNameWithA = writerNameWithA;

            //En fazla başlığa sahip kategori adı
            var mostTitles = _context.Headings.Max(x => x.Category.CategoryName);
            ViewBag.mostTitles = mostTitles;

            //Kategori tablosunda durumu true olan kategoriler ile false olan kategoriler arasındaki sayısal fark
            var statusTrue = _context.Categories.Count(x => x.CategoryStatus == true);
            var statusFalse = _context.Categories.Count(x => x.CategoryStatus == false);
            ViewBag.difference = (statusTrue - statusFalse);

            return View();
            //string session = (string)Session["AdminMail"];
            //ViewBag.a = session;
            //return View();

        }
    }
}

MvcProject/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProject.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }
    }
}

MvcProject/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concretes.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<h1>Yeni kategori ekleme sayfası</h1>
<br />
@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br /><br />
        @Html.Label("Açıklamayı Yazınız")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br /><br />
        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProject/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concretes
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
   
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
 
            <td><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Sil   </a></td>
            <td><a href="/AdminCategory/UpdateCategory/@item.CategoryId" class="btn btn-warning">Güncelle</a></td>
            <td><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }



</table>

<a href="/AdminCategory/AddCategory" class="btn btn-dark">Yeni Kategori</a>

MvcProject/Views/AdminCategory/UpdateCategory.cshtml
@model EntityLayer.Concretes.Category
@{
    ViewBag.Title = "UpdateCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br/>

<h2>Kategori Güncelleme Sayfası</h2>
@using (Html.BeginForm("UpdateCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori Id")
    @Html.TextBoxFor(x => x.CategoryId ,new { @class = "form-control" })
    <br />
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    <br />
    @Html.Label("Açıklama")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    <br/>
    <button class="btn btn-success">Güncelle</button>
</div>
}

MvcProject/Views/Category/AddCategory.cshtml
@model EntityLayer.Concretes.Category
@{
    Layout = null;
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<h1>Yeni kategori ekleme sayfası</h1>
<br/>
@using (Html.BeginForm("AddCategory","Category",FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Kategori Adı")
    @Html.TextBoxFor(x => x.CategoryName)
    @Html.ValidationMessageFor(x => x.CategoryName)
    <br /><br />
    @Html.Label("Açıklamayı Yazınız")
    @Html.TextBoxFor(x => x.CategoryDescription)
    @Html.ValidationMessageFor(x => x.CategoryDescription)
    <br /><br />
    <button>Kaydet</button>
</div>
}


@*<form class="form-group" method="post">
    <input type="text" placeholder="Kategori Adı" name="CategoryName" class="form-control" /> <br/>
    <input type="text" placeholder="Açıklama Giriniz" name="CategoryDescription" class="form-control" />
    <button class="btn btn-primary ">Ekle</button>
</form>*@

MvcProject/Views/Category/GetCategoryList.cshtml
@using EntityLayer.Concretes
@model List<Category>
@{
    Layout = null;
}


<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Ad</th>
        <th>Açıklama</th>
        <th>Durum</th>
    </tr>
    @foreach(var item in Model)
    {
        <tr>
            <td>@item.CategoryId</td>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <td>@item.CategoryStatus</td>
        </tr>
    }



</table>
<br/>
<a href="/Category/AddCategory" class="btn btn-dark">Yeni Kategori</a>

MvcProject/Views/Category/Index.cshtml
@{
    Layout = null;
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<h3>MVC Kamp Tablo Örneği</h3>
<br />

<table class ="table table-bordered ">
    <tr>
        <th>ID</th>
        <th>Adı</th>
        <th>Açıklama</th>
        <th>Durum</th>
        <th>Güncelle</th>

    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Yapıldı</td>
        <td>True</td>
        <td><button class="btn btn-danger">Güncelle</button></td>
    </tr>
    <tr>
        <td>2</td>
        <td>Spor</td>
        <td>Yapıldı</td>
        <td>True</td>
        <td><button class="btn btn-danger">Güncelle</button></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Eğitim</td>
        <td>Yapıldı</td>
        <td>True</td>
        <td><button class="btn btn-danger">Güncelle</button></td>
    </tr>
</table>
<button class="btn btn-info">Yeni Kategori</button>

MvcProject/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>
<br/>
<h3>Mvc Proje Baslangıç</h3>

MvcProject/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MvcProject/Views/Home/Test.cshtml
@{
    ViewBag.Title = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>

MvcProject/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>AdminLTE 3 | Dashboard 3</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminLTE-3.0.4/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to to the body tag
to get the desired effect
|---------------------------------------------------------|
|LAYOUT OPTIONS | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="index3.html" class="brand-link">
                <img src="~/AdminLTE-3.0.4/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                     style="opacity: .8">
                <span class="brand-text font-weight-light">AdminLTE 3</span>
            </a>
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/AdminLTE-3.0.4/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Alexander Pierce</a>
                    </div>
                </div>
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        <li class="nav-item has-treeview menu-open">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tachometer-alt"></i>
                                <p>
                                    Kategoriler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/widgets.html" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Başlıklar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-copy"></i>
                                <p>
                                    Yazarlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chart-pie"></i>
                                <p>
                                    Grafikler
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="pages/charts/chartjs.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 1</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/flot.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 2</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="pages/charts/inline.html" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Grafik 3</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-tree"></i>
                                <p>
                                    Hakkımızda
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    İletişim & Mesajlar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-table"></i>
                                <p>
                                    Yazılar
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/calendar.html" class="nav-link">
                                <i class="nav-icon fas fa-calendar-alt"></i>
                                <p>
                                    Yetkilendirmeler
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="pages/gallery.html" class="nav-link">
                                <i class="nav-icon far fa-image"></i>
                                <p>
                                    Galeri
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon far fa-envelope"></i>
                                <p>
                                    Hata Sayfaları
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Siteye Git
                                </p>
                            </a>

                        </li>
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-apple-alt"></i>
                                <p>
                                    Çıkış yap
                                </p>
                            </a>

                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Main content -->
            <div class="content">
                @RenderBody()
                <!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/AdminLTE-3.0.4/dist/js/adminlte.js"></script>
    <!-- OPTIONAL SCRIPTS -->
    <script src="~/AdminLTE-3.0.4/plugins/chart.js/Chart.min.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>
    <script src="~/AdminLTE-3.0.4/dist/js/pages/dashboard3.js"></script>
</body>
</html>

MvcProject/Views/Shared/_Deneme.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Deneme</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

MvcProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MvcProject/Views/Statistic/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br/>



    <div class="row">
        <div class="col-md-4" >
            <div class="small-box bg-red">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 40px">@ViewBag.totalCategories</sup></h3>
                    <sup style="font-size: 20px">Toplam Kategori Sayısı</sup>
                </div>  <a href="#" class="small-box-footer"></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="small-box bg-success">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 40px">@ViewBag.softwareCategory</sup></h3>
                    <sup style="font-size: 20px">Yazılım Kategorisi Başlık Sayısı</sup>
                </div><a href="#" class="small-box-footer"></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="small-box bg-purple">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 40px">@ViewBag.writerNameWithA</sup></h3>
                    <sup style="font-size: 20px">Yazar adında 'a' harfi geçen yazar sayısı</sup>
                </div><a href="#" class="small-box-footer"></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="small-box bg-cyan">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 40px">@ViewBag.mostTitles</sup></h3>
                    <sup style="font-size: 20px">En fazla başlığa sahip kategori adı</sup>
                </div> <a href="#" class="small-box-footer"></a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="small-box bg-orange">
                <div class="inner" style="text-align: center">
                    <br />
                    <h3><sup style="font-size: 40px">@ViewBag.difference</sup></h3>
                    <sup style="font-size: 20px">Kategori tablosunda durumu true olan kategoriler ile false olan kategoriler arasındaki sayısal fark</sup>
                </div><a href="#" class="small-box-footer"></a>
            </div>
        </div>

    </div>

MvcProject/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Deneme.cshtml";
}

<h2>Index</h2>